# CMake generated Testfile for 
# Source directory: /home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests
# Build directory: /home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(DequeInsertBack.OneItemAdd "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsertBack.OneItemAdd")
add_test(DequeInsertFront.OneItemAdd "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsertFront.OneItemAdd")
add_test(DequeInsert.EmptyString "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsert.EmptyString")
add_test(DequeInsertBack.ThreeItemAdd "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsertBack.ThreeItemAdd")
add_test(DequeInsertFront.ThreeItemAdd "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsertFront.ThreeItemAdd")
add_test(DequeInsert.FrontThenBack "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsert.FrontThenBack")
add_test(DequeInsert.BackThenFront "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsert.BackThenFront")
add_test(DequeInsertBack.ARRSIZEPlusOne "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsertBack.ARRSIZEPlusOne")
add_test(DequeInsertFront.ARRSIZEPlusOne "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsertFront.ARRSIZEPlusOne")
add_test(DequeInsertBack.50RandomElements "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsertBack.50RandomElements")
add_test(DequeInsertFront.50RandomElements "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsertFront.50RandomElements")
add_test(DequeInsertBack.5x1000RandomElements "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsertBack.5x1000RandomElements")
add_test(DequeInsertFront.5x1000RandomElements "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeInsertFront.5x1000RandomElements")
add_test(Deque.ConstructionDestruction "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=Deque.ConstructionDestruction")
add_test(Deque.NoElements "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=Deque.NoElements")
add_test(Deque.Front_PushBack "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=Deque.Front_PushBack")
add_test(Deque.Front_PushFront "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=Deque.Front_PushFront")
add_test(Deque.Back_PushBack "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=Deque.Back_PushBack")
add_test(Deque.Back_PushFront "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=Deque.Back_PushFront")
add_test(DequeSet.OneItem "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeSet.OneItem")
add_test(DequeSet.First "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeSet.First")
add_test(DequeSet.Last "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeSet.Last")
add_test(DequeSet.Middle "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeSet.Middle")
add_test(DequeSet.50x50RandomElements "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeSet.50x50RandomElements")
add_test(DequeRemove.OneItemFront "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.OneItemFront")
add_test(DequeRemove.OneItemBack "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.OneItemBack")
add_test(DequeRemove.RepeatedOneEleRemoveBack "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.RepeatedOneEleRemoveBack")
add_test(DequeRemove.RepeatedOneEleRemoveFront "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.RepeatedOneEleRemoveFront")
add_test(DequeRemove.Head3Elements "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.Head3Elements")
add_test(DequeRemove.Tail3Elements "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.Tail3Elements")
add_test(DequeRemove.AtARRSIZE "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.AtARRSIZE")
add_test(DequeRemove.AtARRSIZEPlusOne "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.AtARRSIZEPlusOne")
add_test(DequeRemove.SongOfBackAndFront "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.SongOfBackAndFront")
add_test(DequeRemove.50ElementsFromBack "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.50ElementsFromBack")
add_test(DequeRemove.50ElementsFromFront "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_tests" "--gtest_filter=DequeRemove.50ElementsFromFront")
add_test(DequeRuntime.Get "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_runtime_tests" "--gtest_filter=DequeRuntime.Get")
add_test(DequeRuntime.PushBack "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_runtime_tests" "--gtest_filter=DequeRuntime.PushBack")
add_test(DequeRuntime.PushFront "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_runtime_tests" "--gtest_filter=DequeRuntime.PushFront")
add_test(DequeRuntime.PopFront "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_runtime_tests" "--gtest_filter=DequeRuntime.PopFront")
add_test(DequeRuntime.PopBack "/home/cs104/hw-ykelty/hw4/hw4_tests/deque_tests/deque_runtime_tests" "--gtest_filter=DequeRuntime.PopBack")
